### ISSUE TITLE
Texture.data and flipY

### ISSUE THREAD

**Issue by lucasdomanico** [tsherif/picogl.js#160] opened 2019-11-12 03:43 UTC
Hello again,
It seems that in `Texture.data()`, the `texSubImage2D` call uses the last value set for `pixelStorei(GL.UNPACK_FLIP_Y_WEBGL)` and doesn't use the texture's `flipY`.
If I understand this correctly, it can be fixed by adding in `Texture.data()` this again after binding.
```javascript
    data(data) {
        if (!Array.isArray(data)) {
            DUMMY_UNIT_ARRAY[0] = data;
            data = DUMMY_UNIT_ARRAY;
        }

        let numLevels = this.mipmaps ? data.length : 1;
        let width = this.width;
        let height = this.height;
        let depth = this.depth;
        let generateMipmaps = this.mipmaps && data.length === 1;
        let i;

        this.bind(Math.max(this.currentUnit, 0));
        this.gl.pixelStorei(GL.UNPACK_FLIP_Y_WEBGL, this.flipY); // <- here
```

**Comment by tsherif** [comment] 2019-11-12 15:25
Hmmm... that's odd. I thought pixel store parameters were part of texture state. Thanks for reporting.

**Comment by tsherif** [comment] 2019-11-13 11:24
Turns out I was totally wrong. Pixel unpack parameters are part of the global GL state. This will be fixed in the next patch (+ a regression test!)

**Closed** 2019-11-13 12:54 UTC
